# Configuración para Gateway Bridge
[general]
# Nivel de registro
log_level="info"

# Configuración para backend UDP - para gateways con UDP Packet Forwarder
[backend.semtech_udp]
udp_bind="0.0.0.0:1700"

# Configuración para backend MQTT - para gateways con MQTT forwarder
[backend.mqtt]
server="tcp://mosquitto:1883"
topic_prefix="au915"

# Configuración de la integración MQTT
[integration.mqtt]
server="tcp://mosquitto:1883"
topic_prefix="au915"
event_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="gateway/{{ .GatewayID }}/command/#"

# Configuración del marshaler
[integration.mqtt.marshaler]
type="protobuf"