version: "3.9"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    ports:
      - "8081:8081"  # Cambiado para evitar conflicto
    volumes:
      - ./chirpstack:/etc/chirpstack
    depends_on:
      - redis
      - postgres
    networks:
      - coolify

  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8081 --bind 0.0.0.0:8090 --insecure
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      #- ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chirpstack
      - POSTGRES_PASSWORD=chirpstack
      - POSTGRES_DB=chirpstack
    networks:
      - coolify

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --save 60 100 --appendonly no
    volumes:
      - redisdata:/data
    networks:
      - coolify

volumes:
  redisdata:
  pgdata:


networks:
  coolify:
    external: true
