version: "3"

services:
  # ChirpStack Application Server
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      postgres:
        condition: service_healthy  # Espera a que PostgreSQL esté realmente listo
      mosquitto:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - "8081:8080"

  # ChirpStack Gateway Bridge - Para gateway con MQTT forwarder
  chirpstack-gateway-bridge-mqtt:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      # Configurado para AU915
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/command/#
      - INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
    depends_on:
      - mosquitto

  # ChirpStack Gateway Bridge - Para gateway con UDP Packet Forwarder
  chirpstack-gateway-bridge-udp:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - "1700:1700/udp"
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      # Configurado para AU915
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/command/#
      - INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
    depends_on:
      - mosquitto

  # Servidor REST API de ChirpStack
  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    environment:
      - SERVER=chirpstack:8080
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack

  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis database
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MQTT broker
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    volumes:
      - ./configuration/mosquitto:/mosquitto/config
      #- mosquitto_data:/mosquitto/data
      #- mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"

volumes:
  postgres_data:
  redis_data:
  #mosquitto_data:
  #mosquitto_log: