version: "3"

services:
   # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    #command: -c /docker-entrypoint-initdb.d
    # networks:
    #   - chirpstack-net
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-chirpstack}
      - POSTGRES_USER=${POSTGRES_USER:-chirpstack}
      - POSTGRES_DB=${POSTGRES_DB:-chirpstack}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chirpstack"]
      interval: 5s
      timeout: 50s
      retries: 5   
      start_period: 100s
  # ChirpStack Application Server
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    # networks:
    #   - chirpstack-net
    volumes:
      - ./configuration/chirpstack:/etc/chirpstack
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - "8081:8080"

  # ChirpStack Gateway Bridge - Para gateway con MQTT forwarder
  # chirpstack-gateway-bridge-mqtt:
  #   image: chirpstack/chirpstack-gateway-bridge:4
  #   restart: unless-stopped
  #   volumes:
  #     - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
  #   environment:
  #     # Configurado para AU915
  #     - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/event/{{ .EventType }}
  #     - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/state/{{ .StateType }}
  #     - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/command/#
  #     - INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
  #   depends_on:
  #     - mosquitto

  #ChirpStack Gateway Bridge - Para gateway con UDP Packet Forwarder
  chirpstack-gateway-bridge-udp:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - "1700:1700/udp"
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      # Configurado para AU915
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=au915/gateway/{{ .GatewayID }}/command/#
      - INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
    depends_on:
      - mosquitto

  # Servidor REST API de ChirpStack
  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    # networks:
    #   - chirpstack-net
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    #environment:
    #  - SERVER=chirpstack:8080
    ports:
      - "8090:8090"
    depends_on:
      - chirpstack

  # Redis database
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    # networks:
    #   - chirpstack-net
    volumes:
      - redis_data:/data
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MQTT broker - Usando entrypoint para generar configuración
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      #- "1883:1883"
      - "1884:1884"      
    # networks:
    #   - chirpstack-net
    volumes:
      - mosquitto-config:/mosquitto/config
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - ALLOW_ANONYMOUS=${ALLOW_ANONYMOUS:-false}
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: >
       sh -c "
        # Inicializar archivo de configuración limpio
         echo '' > /mosquitto/config/mosquitto.conf


        # Empezar con configuración por listener
        echo 'per_listener_settings true' > /mosquitto/config/mosquitto.conf

        # Listener sin autenticación (interno)
        echo 'listener 1883' >> /mosquitto/config/mosquitto.conf
        echo 'allow_anonymous true' >> /mosquitto/config/mosquitto.conf

        echo '' >> /mosquitto/config/mosquitto.conf  # Separador visual

        # Listener con autenticación (externo)
        if [ \"$ALLOW_ANONYMOUS\" = \"false\" ]; then
          echo 'listener 1884' >> /mosquitto/config/mosquitto.conf
          echo 'allow_anonymous "false' >> /mosquitto/config/mosquitto.conf
          echo 'password_file /mosquitto/config/passwords' >> /mosquitto/config/mosquitto.conf

          # Crear archivo de contraseñas
          touch /mosquitto/config/passwords
          chmod 0700 /mosquitto/config/passwords
          chown root:root /mosquitto/config/passwords

          mosquitto_passwd -b -c /mosquitto/config/passwords \"$MQTT_USERNAME\" \"$MQTT_PASSWORD\"
          chown mosquitto:mosquitto /mosquitto/config/passwords
        fi

        # Ejecutar mosquitto
        exec mosquitto -c /mosquitto/config/mosquitto.conf
        "

volumes:
  postgres_data:
  redis_data:
  mosquitto-config:

# networks:
#   chirpstack-net:
#     driver: bridge