version: "3.9"

services:
  chirpstack:
    image: chirpstack/chirpstack:4
    command: --config /etc/chirpstack
    ports:
      - "8085:8080"  # Cambiado para evitar conflicto
    volumes:
      - ./chirpstack/chirpstack.toml:/etc/chirpstack/chirpstack.toml
    depends_on:
      - redis
      - postgres
    networks:
      - coolify

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - coolify

  redis:
    image: redis:7-alpine
    networks:
      - coolify

volumes:
  pgdata:

networks:
  coolify:
    external: true
