# Configuración global de ChirpStack
[logging]
level="info"

# PostgreSQL settings.
[postgresql]
dsn="postgres://chirpstack:chirpstack@postgres/chirpstack?sslmode=disable"

# Redis settings
[redis]
servers=[
  "redis:6379",
]

# API interface
[api]
bind="0.0.0.0:8080"

# Integración con el broker MQTT
[integration.mqtt]
server="tcp://mosquitto:1883"
event_topic_template="au915/application/{{ .ApplicationID }}/device/{{ .DeviceInfo.DevEUI }}/event/{{ .EventType }}"
state_topic_template="au915/application/{{ .ApplicationID }}/device/{{ .DeviceInfo.DevEUI }}/state/{{ .StateType }}"
command_topic_template="au915/application/{{ .ApplicationID }}/device/{{ .DeviceInfo.DevEUI }}/command/{{ .CommandType }}"

# Regiones LoRaWAN habilitadas
[network]
enabled_regions=[
  "au915_0", # Región AU915 - Primer bloque de canales
]

# Gateway backend settings.
[gateway]
# Tiempo en segundos que el gateway puede estar inactivo antes de marcarlo como offline.
client_cert_lifetime="24h0m0s"

# Configuración del servicio de unión (join-server)
[join_server]
bind="0.0.0.0:8003"