# Configuración global de ChirpStack
[logging]
level="info"

# PostgreSQL settings.
[postgresql]
  # PostgreSQL DSN.
  #
  # Format example: postgres://<USERNAME>:<PASSWORD>@<HOSTNAME>/<DATABASE>?sslmode=<SSLMODE>.
  #
  # SSL mode options:
  #  * disable - Do not use TLS
  #  * prefer - Attempt to connect with TLS but allow sessions without
  #  * require - Require the use of TLS
  dsn="postgres://chirpstack:chirpstack@$POSTGRES_HOST/chirpstack?sslmode=disable"

  # Max open connections.
  #
  # This sets the max. number of open connections that are allowed in the
  # PostgreSQL connection pool.
  max_open_connections=10

  # Min idle connections.
  #
  # This sets the min. number of idle connections in the PostgreSQL connection
  # pool (0 = equal to max_open_connections).
  min_idle_connections=0


# Redis settings
[redis]
servers=[
  "redis://redis:6379",
]

# API interface
[api]
bind="0.0.0.0:8080"

# Integración con el broker MQTT
[integration.mqtt]
server="tcp://mosquitto:1883"
event_topic_template="au915/application/{{ .ApplicationID }}/device/{{ .DeviceInfo.DevEUI }}/event/{{ .EventType }}"
state_topic_template="au915/application/{{ .ApplicationID }}/device/{{ .DeviceInfo.DevEUI }}/state/{{ .StateType }}"
command_topic_template="au915/application/{{ .ApplicationID }}/device/{{ .DeviceInfo.DevEUI }}/command/{{ .CommandType }}"

# Regiones LoRaWAN habilitadas
[network]
enabled_regions=[
  "au915_0", # Región AU915 - Primer bloque de canales
]

# Gateway backend settings.
[gateway]
# Tiempo en segundos que el gateway puede estar inactivo antes de marcarlo como offline.
client_cert_lifetime="24h0m0s"

# Configuración del servicio de unión (join-server)
[join_server]
bind="0.0.0.0:8003"