[meta]
name="ChirpStack Coolify AU915"

[postgresql]
dsn="postgres://{{env "POSTGRES_USER"}}:{{env "POSTGRES_PASSWORD"}}@postgres/{{env "POSTGRES_DB"}}?sslmode=disable"

[redis]
url="redis://redis:6379"

[network]
net_id="000000"
enabled_regions=["au915"]

[integration.mqtt]
server="tcp://mosquitto:1883"
username="{{env "MQTT_USERNAME"}}"
password="{{env "MQTT_PASSWORD"}}"
json=true

[api]
bind="0.0.0.0:8080"
public_host="http://localhost:8085"

# Activar Web UI si la usas
[web]
public_host="https://chirpstack.grafo.cloud"

# AU915 configura 8 canales de uplink y un downlink
[region.au915]
# Define los canales habilitados: sub-banda 1 (CH0-CH7 + 64)
enabled_uplink_channels=[
  0, 1, 2, 3, 4, 5, 6, 7, 64
]

# Downlink: DR8 a DR13
rx1_delay=1
rx2_dr=8
