[logging]
level="info"

[postgresql]
dsn="postgres://chirpstack:chirpstack@postgres/chirpstack?sslmode=disable"

[redis]
url="redis://redis:6379"

[mqtt]
server="tcp://mqtt.grafo.cloud:1883"
username="${SERVICE_USER_MOSQUITTO}"
password="${SERVICE_PASSWORD_MOSQUITTO}"

[api]
bind="0.0.0.0:8081"  # Cambiado de 8080 a 8081 para evitar conflicto

[network.network_server]
deduplication_delay="200ms"
device_session_ttl="24h"

[[network.network_server.band]]
name="EU868"
uplink_frequencies=[868100000, 868300000, 868500000]

[[network.network_server.band.network_settings.extra_channels]]
frequency=867100000
min_dr=0
max_dr=5

[[network.network_server.band.network_settings.extra_channels]]
frequency=867300000
min_dr=0
max_dr=5

[[network.network_server.band.network_settings.extra_channels]]
frequency=867500000
min_dr=0
max_dr=5

[[network.network_server.band.network_settings.extra_channels]]
frequency=867700000
min_dr=0
max_dr=5

[[network.network_server.band.network_settings.extra_channels]]
frequency=867900000
min_dr=0
max_dr=5

[network.gateway.backend]
type="mqtt"

[network.gateway.backend.mqtt]
server="tcp://mqtt.grafo.cloud:1883"
username="${SERVICE_USER_MOSQUITTO}"
password="${SERVICE_PASSWORD_MOSQUITTO}"
event_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"
command_topic_template="gateway/{{ .GatewayID }}/command/{{ .CommandType }}"
